### PR TITLE
fix: fix typerror in the user servise ts file

### PR DESCRIPTION
**Pull request by SergeInGithub**
fix typerror in the user.service.ts file and wherever else its called and imported... Also, this as a trial to test whether i'll be added as a contributor after i fixed my local git credentials

### CODE REVIEW

**Review by shyakadavis — APPROVED** [review]
LGTM

**Review by emilenfc — APPROVED** [review]
okay

**Review by ISHIMWE-Aime — CHANGES_REQUESTED** [review]
Try to fix does errors

**Review by ISHIMWE-Aime — APPROVED** [review]
LGTM

**Pull request closed without merging**
