### PR TITLE
ft: add code cleanup, add product search, add cart ft

### PR DESCRIPTION
**Pull request by shyakadavis**
# 🌍 Description 🧭

- I did some generic code cleanup, in terms of adhering to the initial folder structure. For example file naming conventions, how we import and export, and basically how we are structuring the code. 
- I also did a search ft, whereby a user can search for a product by name, category, or price range.
- I also added the cart ft, viewing it, ```but not its total```, adding a new item, and clearing the cart. 
- I also added authentication middleware (isAuth, isSeller, isAdmin).
- We also modified the Dockerfile and docker-compose, and can now safely say we have a development-ready image.
- Also added a pull_request_template in the ./github folder.

- 🏬 Features

```text
     🪜 Stories #184361231 , #184361227 , 184361229 , 184361230
```

## 🧶 Type of change  🐾

- [x] New feature (non-breaking change which adds functionality)

## 🧪 How Has This Been Tested? 🧑‍💻

I set up tests for the signup, login, email confirmation, get all users, and get user by id routes, cart tests, and product tests(by @SergeInGithub) .

All tests are passing locally.
⚠️ Remember to first set up the ```NODE_ENV = test``` in your ```.env``` so that the db that will be used for testing is ```testcypher```. Be sure to fist create that db, and everything else is as normal. Or, just rename the ```.env.example``` file to ```.env``` and fill in the necessary keys.

- [x] User Sign Up
- [x] User Log In
- [x] Confirm User Registration
- [x] Get all Users
- [x] Get User By Id
- [x] Search for a Product
- [x] Add Items to Cart
- [x] View Cart
- [x] Clear Cart

**Failing Test Details**:

- None

## ✅ Checklist

- [x] I have performed a self-review of my own code
- [x] My code follows the style guidelines of this project
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

## ☑️ To-do

- [ ] Add the controller function to calculate a cart's total.
## 🐪 Production Ready 🩺

- [ ] Deploy to production ❌ 

## 📓 Additional Notes

- I need help improving the Docker image, in terms of having it ready for production.
- I need help in deploying this. Haven't still figured it out.
- I wonder if there is something we can improve when handling role-based authentication 🤔 
- 🍎 The circleci tests are failing, but locally they are passing. 🥲 
We think it has something to do with the yaml scripts. We shall take a look at all that later.

### CODE REVIEW

**Comment by shyakadavis** [comment]
Temporarily closed this P.R to work on a feature in case it is merged before I push again.

**Review by SergeInGithub — APPROVED** [review]
LGTM

**Review by ISINGIZWEcla — COMMENTED** [review]
LGTM

**Comment by mucyoalexaxel** [comment]
@shyakadavis Squash the commit messages.

**Pull request merged**
