### PR TITLE
Ft google login

### PR DESCRIPTION
**Pull request by ISHIMWE-Aime**

### CODE REVIEW

**Review by musllim — APPROVED** [review]
okay, that looks good

**Review by emilenfc — APPROVED** [review]
very nice

**Review by emilenfc — APPROVED** [review]
very nice, but try run `pnpm coverage` to see if it work

**Review by SergeInGithub — DISMISSED** [review]
LGTM

**Review by emilenfc — DISMISSED** [review]

**Review by emilenfc — DISMISSED** [review]

**Review by musllim — APPROVED** [review]

**Comment by mucyoalexaxel** [comment]
@ISHIMWE-Aime can you squash all commits into one commit.

**Review by emilenfc — APPROVED** [review]

**Pull request merged**
