### PR TITLE
fix: add load .env in development only

### PR DESCRIPTION
**Pull request by musllim**
add env variables and add create db cmd
add command create users

### CODE REVIEW

**Review by emilenfc — APPROVED** [review]

**Review by shyakadavis — CHANGES_REQUESTED** [review]
You forgot to resolve the conflicts in test.spec.ts

**Review by shyakadavis — APPROVED** [review]
LGTM

**Comment by SergeInGithub** [comment]
LGTM

**Review by SergeInGithub — APPROVED** [review]
LGTM

**Pull request merged**
