### PR TITLE
add ft: admin should be able to disable any user account #184361215

### PR DESCRIPTION
**Pull request by musllim**
add documentation and unit testing for this feature

WHEN a user is suspected or proved to have violated the terms of service of the application THEN admin is able to trigger an action to block usage of a particular account and an email sent to the user with reasons fro the block.

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

# Type of change

Please check the options that are relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature or Enhancement (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have created a loom video for the new feature or enhancement
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [ x New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by mucyoalexaxel — DISMISSED** [review]
LGTM

**Comment by shyakadavis** [comment]
I couldn't find the file to leave my comment on, but you forgot something important.

`What if they try to login after that?`

After this PR, #112 , you can now go ahead and a new `case` to the switch logic, so that whenever they try to log in, and there account is disabled, it should throw a relevant error.

**Review by shyakadavis — CHANGES_REQUESTED** [review]
I couldn't find the file to leave my comment on, but you forgot something important.

**`What if they try to log in after that?`**

After this #112 , you can now go ahead in the `checkLoginIntegrity` utility function, and a new `case` to the switch logic, so that whenever they try to log in, and their account is disabled, it should throw a relevant error.

🥂

**Review by shyakadavis — DISMISSED** [review]
LGTM ⏳

**Review by SergeInGithub — DISMISSED** [review]
LGTM

**Review by mucyoalexaxel — DISMISSED** [review]

**Pull request merged**
